### ISSUE TITLE
Great job And... it's now possible to use Apple's MDLAsset to load the Obj files 

### ISSUE THREAD

**Issue by johndpope** [toddjohn/OBJViewer-iOS#1]
https://forums.developer.apple.com/thread/3979

```
    let bundle = NSBundle.mainBundle()  
    let path = bundle.pathForResource("Model", ofType: "obj")  
    let url = NSURL(fileURLWithPath: path!)  
    let asset = MDLAsset(URL: url)  
    let scene = SCNScene(MDLAsset: asset)  
```

By chance, did you try to load fxb files in apple scenekit? 
http://www.autodesk.com/products/fbx/overview

**Comment by toddjohn** [comment]
Thanks! I was looking to improve the performance of the code when I figured out that you can convert the model in Xcode, so parsing obj files isn't necessary at all. I didn't know about using MDLAsset -- thanks for the tip. 

I haven't done anything with fxb files, since I'm not familiar with that format. My sample model files are all obj format.

**Comment by johndpope** [comment]
thanks @toddjohn - I'm doing some spring cleaning on old github tickets. 
135 to go.
